version: '3.7'
services:

  #Postgresql Service
  nj-db:
    image: postgres
    container_name: nj-node-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nj
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: nathanjms_api
    volumes:
      - ./postgres-data:/postgresql/data
    ports:
      - '5433:5432'

  nodejs:
    image: node
    container_name: nodejs
    restart: unless-stopped
    user: "www-data:www-data"
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev